version: '3.8'

services:
  bestshop:
    image: bestshop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=bestshop;User Id=sa;Password=Chathura@1991#;TrustServerCertificate=true;
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Chathura@1991#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
